package views;

import controller.CustomerController;
import db.DBConnection;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dto.CustomerDTO;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sanu-vithanage
 */
public class CustomerForm extends javax.swing.JFrame {

    DefaultTableModel dtm;

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
        dtm = (DefaultTableModel) tblCustomer.getModel();
        loadAllCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCusName = new javax.swing.JTextField();
        txtCusAddress = new javax.swing.JTextField();
        txtCusSalary = new javax.swing.JTextField();
        txtCusID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 494));
        setSize(new java.awt.Dimension(460, 494));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 95, 280, 44));
        getContentPane().add(txtCusAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 165, 280, 44));
        getContentPane().add(txtCusSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 239, 280, 44));

        txtCusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtCusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 44));

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerID", "CustomerName", "CustomerAddress", "CustomerSalary"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 420, 170));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 90, 30));

        jButton2.setText("Add");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 90, 30));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 90, 30));

        jLabel1.setText("Customer Salary");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel2.setText("Customer ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("Customer Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 90, 30));

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 90, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadAllCustomers();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String customerID = txtCusID.getText();
            String customerName = txtCusName.getText();
            String customerAddress = txtCusAddress.getText();
            double customerSalary = Double.parseDouble(txtCusSalary.getText());

            CustomerDTO dto = new CustomerDTO(customerID, customerName, customerAddress, customerSalary);
            boolean addCustomer = CustomerController.addCustomer(dto);
            if (addCustomer) {
                JOptionPane.showMessageDialog(this, "Customer Aded..!");
                clearAll();
                loadAllCustomers();
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Aded..!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            String customerID = txtCusID.getText();
            boolean deleteCustomer = CustomerController.deleteCustomer(customerID);
            if (deleteCustomer) {
                JOptionPane.showMessageDialog(this, "Deleted");
                clearAll();
                loadAllCustomers();
            } else {
                JOptionPane.showMessageDialog(this, "Not Deleted..!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusIDActionPerformed

        try {
            String customerID = txtCusID.getText();
            CustomerDTO searchCustomer = CustomerController.searchCustomer(customerID);
            if (searchCustomer != null) {
                txtCusID.setText(searchCustomer.getId());
                txtCusName.setText(searchCustomer.getName());
                txtCusAddress.setText(searchCustomer.getAddress());
                txtCusSalary.setText(Double.toString(searchCustomer.getSalary()));

                Connection connection = DBConnection.getInstance().getConnection();

                InputStream is = this.getClass().getResourceAsStream("/reports/uniqueCustomer.jasper");
                HashMap map = new HashMap();
                map.put("id", customerID);
                JasperPrint fillReport = JasperFillManager.fillReport(is, map, connection);
                JasperViewer.viewReport(fillReport, false);

            } else {
                JOptionPane.showMessageDialog(this, "No Customer");
                clearAll();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_txtCusIDActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            Connection connection = DBConnection.getInstance().getConnection();

            InputStream is = this.getClass().getResourceAsStream("/reports/CustomerReport.jasper");
            JasperPrint fillReport = JasperFillManager.fillReport(is, null, connection);
            JasperViewer.viewReport(fillReport, false);

            InputStream is2 = this.getClass().getResourceAsStream("/reports/customerSalary.jasper");
            JasperPrint fillReport2 = JasperFillManager.fillReport(is2, null, connection);
            JasperViewer.viewReport(fillReport2, false);

        } catch (JRException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        int row = tblCustomer.getSelectedRow();
        txtCusID.setText(dtm.getValueAt(row, 0).toString());
        txtCusName.setText(dtm.getValueAt(row, 1).toString());
        txtCusAddress.setText(dtm.getValueAt(row, 2).toString());
        txtCusSalary.setText(dtm.getValueAt(row, 3).toString());

    }//GEN-LAST:event_tblCustomerMouseClicked

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        System.out.println("Mouse is Entered");
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        System.out.println("Mouse Exited");
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        System.out.println("Mouse is Pressed");
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        System.out.println("Released");
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String customerID = txtCusID.getText();
            String customerName = txtCusName.getText();
            String customerAddress = txtCusAddress.getText();
            double customerSalary = Double.parseDouble(txtCusSalary.getText());
            CustomerDTO dto = new CustomerDTO(customerID, customerName, customerAddress, customerSalary);
            boolean updateCustomer = CustomerController.updateCustomer(dto);
            if (updateCustomer) {
                JOptionPane.showMessageDialog(this, "Customer Updated..!");
                clearAll();
                loadAllCustomers();
            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Updated..!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    public void clearAll() {
        txtCusID.setText("");
        txtCusName.setText("");
        txtCusAddress.setText("");
        txtCusSalary.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtCusAddress;
    private javax.swing.JTextField txtCusID;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtCusSalary;
    // End of variables declaration//GEN-END:variables

    private void loadAllCustomers() {
        clearAll();
        try {
            dtm.setRowCount(0);
            ArrayList<CustomerDTO> allCustomers = CustomerController.getAllCustomers();
            for (CustomerDTO c : allCustomers) {
                Object ob[] = {c.getId(), c.getName(), c.getAddress(), c.getSalary()};
                dtm.addRow(ob);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }
}
